/**
 * UltraTech Portal - React Build Pipeline
 * Zero-dependency compiler using standalone Babel.
 * Run with: agy-node.cmd build.js [--watch]
 */

const fs = require('fs');
const path = require('path');

const Babel = require('./vendor/babel.min.js');

const SRC_DIR = path.join(__dirname, 'src');
const OUTPUT_FILE = path.join(__dirname, 'js', 'app.js');

function build() {
  const startTime = Date.now();
  console.log('[Build] Compiling React application...');

  if (!fs.existsSync(SRC_DIR)) {
    console.error(`[Build Error] Source directory not found: ${SRC_DIR}`);
    return false;
  }

  const fileOrder = [
    // 1. Utilities and helpers
    'src/utils/helpers.js',
    'src/utils/icons.jsx',
    // 2. Context & Hooks
    'src/context/StoreContext.jsx',
    // 3. Modals & Drawers
    'src/components/modals/LoginModal.jsx',
    'src/components/modals/NotificationsDrawer.jsx',
    'src/components/modals/ProofDrawer.jsx',
    'src/components/modals/EscalateModal.jsx',
    'src/components/modals/DocPreviewModal.jsx',
    'src/components/modals/CreateEventModal.jsx',
    'src/components/modals/AssignCandidatesModal.jsx',
    'src/components/modals/PromotionModal.jsx',
    'src/components/modals/EmployeeDetailModal.jsx',
    // 4. Shell & Common Components
    'src/components/TopBar.jsx',
    'src/components/Sidebar.jsx',
    'src/components/MobileBottomNav.jsx',
    'src/components/ToastContainer.jsx',
    // 5. Views - Employee
    'src/views/employee/EmployeeHome.jsx',
    'src/views/employee/EmployeeProfile.jsx',
    'src/views/employee/EmployeeTrainings.jsx',
    'src/views/employee/EmployeeRequest.jsx',
    'src/views/employee/EmployeeNotifications.jsx',
    // 6. Views - Head
    'src/views/head/HeadHome.jsx',
    'src/views/head/HeadRequest.jsx',
    'src/views/head/HeadTeam.jsx',
    'src/views/head/HeadSignoffs.jsx',
    'src/views/head/HeadRequestStatus.jsx',
    'src/views/head/HeadReports.jsx',
    // 7. Views - HR Admin
    'src/views/hr/HrHome.jsx',
    'src/views/hr/HrCycle.jsx',
    'src/views/hr/HrRequests.jsx',
    'src/views/hr/HrCalendar.jsx',
    'src/views/hr/HrDirectory.jsx',
    'src/views/hr/HrEscalations.jsx',
    'src/views/hr/HrPromotions.jsx',
    'src/views/hr/HrReports.jsx',
    // 8. Main App & Mount
    'src/App.jsx',
    'src/main.jsx'
  ];

  let combinedSource = `/**
 * UltraTech Training Portal - Compiled React Application
 * Auto-generated by build.js
 */

import { store } from './store.js';

const { useState, useEffect, useMemo, useRef, useCallback, createContext, useContext } = React;

`;

  for (const relPath of fileOrder) {
    const fullPath = path.join(__dirname, relPath);
    if (fs.existsSync(fullPath)) {
      const content = fs.readFileSync(fullPath, 'utf8');
      const sanitized = content
        .replace(/^import\s+.*?from\s+['"].*?['"];?\s*$/gm, '')
        .replace(/^const\s+\{[^}]*\}\s*=\s*React;?\s*$/gm, '')
        .replace(/^export\s+default\s+/gm, '')
        .replace(/^export\s+\{[^}]*\};?\s*$/gm, '')
        .replace(/^export\s+(const|function|class|let|var)\s+/gm, '$1 ');
      
      combinedSource += `// --- File: ${relPath} ---\n${sanitized}\n\n`;
    }
  }

  try {
    const result = Babel.transform(combinedSource, {
      presets: [
        ['react', { runtime: 'classic' }]
      ],
      compact: false
    });

    const outDir = path.dirname(OUTPUT_FILE);
    if (!fs.existsSync(outDir)) {
      fs.mkdirSync(outDir, { recursive: true });
    }

    fs.writeFileSync(OUTPUT_FILE, result.code, 'utf8');
    const elapsed = Date.now() - startTime;
    console.log(`[Build Success] Compiled to ${OUTPUT_FILE} in ${elapsed}ms`);
    return true;
  } catch (err) {
    console.error(`[Build Error] Failed to compile JSX:`, err.message);
    if (err.loc) {
      console.error(`At line ${err.loc.line}, column ${err.loc.column}`);
    }
    return false;
  }
}

if (require.main === module) {
  const isWatch = process.argv.includes('--watch');
  build();

  if (isWatch) {
    console.log(`[Build] Watching ${SRC_DIR} for changes...`);
    fs.watch(SRC_DIR, { recursive: true }, (eventType, filename) => {
      if (filename && (filename.endsWith('.js') || filename.endsWith('.jsx'))) {
        console.log(`[Watch] File changed: ${filename}`);
        build();
      }
    });
  }
}

module.exports = { build };
